name: github action

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
            node-version: '20.x'

      - name: Install dependencies
        run: |
         cd backend
         npm install
         
      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Add host to known hosts
        run: |
         ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to virtual machine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd backend
            scp -r ./* ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }}:/node
            ssh ${{ secrets.VM_USERNAME }}@${{ secrets.VM_HOST }} "cd /node && node index.js"
            echo "Deployment and execution completed."
